version: "3"

services:
    app:
        container_name: architecture-patterns-app
        build: .
        depends_on:
            - postgres
        environment:
            - DB_HOST=postgres
            - DB_PORT=5432
            - DB_USER=allocation
            - DB_PASSWORD=abc123
            - DB_DRIVER=postgresql+psycopg2
        volumes:
            - app:/allocation:/allocation
            - app:/tests:/tests
        networks:
            - server
        links:
            - postgres
        ports:
            - "8000:8000"

    postgres:
        image: postgres:15.4
        container_name: architecture-patterns-db
        environment:
            - POSTGRES_USER=allocation
            - POSTGRES_PASSWORD=abc123
            - POSTGRES_DB=warehouse
        networks:
            - server
        ports:
            - "5432:5432"
        volumes:
            - database:/var/lib/postgresql/data

networks:
    server: { }

volumes:
    app:
    database:
