# Test your FastAPI endpoints

GET http://localhost:8000/
Accept: application/json

###

GET http://localhost:8000/batch/batch1
Accept: application/json


###


POST http://localhost:8000/allocate
Content-Type: application/json

{
	"reference": "some reference",
	"sku": "sku2",
	"quantity": 2
}



